name: Manual Docker Image Release (auto from package.json)

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  # This is my test repository path; update it to your actual Docker Hub repo
  IMAGE_NAME: garenmtech1981/wms

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Read version from package.json
        id: ver
        shell: bash
        run: |
          # 1) package.json must be at the repo root
          #    (if not, change the path to ./path/package.json)
          if [ ! -f package.json ]; then
            echo "::error::package.json not found at repository root"
            exit 1
          fi

          # 2) Read the version
          RAW=$(node -e "try{console.log(require('./package.json').version || '')}catch(e){process.exit(1)}")
          echo "package.json version: $RAW"

          # Accept 'v2.3.4' and strip the leading 'v'
          VERSION="${RAW#v}"

          # 3) Validate semver with a Node regex (pre-release/build metadata allowed)
          node -e "const v='${VERSION}'; const ok=/^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/.test(v); if(!ok){console.error('Invalid semver version:', v); process.exit(1)}"

          # 4) Export
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t "${{ env.IMAGE_NAME }}:${{ env.VERSION }}" \
            -t "${{ env.IMAGE_NAME }}:latest" \
            .

      - name: Push image
        run: |
          docker push "${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
          docker push "${{ env.IMAGE_NAME }}:latest"

      - name: Summary
        run: echo "Pushed $IMAGE_NAME:${VERSION} and $IMAGE_NAME:latest"
