name: PR Label Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
      - edited




permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr-release-label:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR has exactly one of: Major / Minor / Patch
        uses: actions/github-script@v7
        with:
          script: |
            const allowed = new Set(["Major","Minor","Patch"]);

            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });

            const names = labels.map(l => l.name);
            const matched = names.filter(n => allowed.has(n));

            if (matched.length === 0) {
              core.setFailed(
                "This pull request must have exactly ONE of: Major, Minor, Patch."
              );
              return;
            }

            if (matched.length > 1) {
              core.setFailed(
                `Only one release label is allowed, but found: ${matched.join(", ")}.`
              );
              return;
            }

            // const others = names.filter(n => !allowed.has(n));
            // if (others.length > 0) {
            //   core.setFailed(
            //     `Only a single release label (Major/Minor/Patch) is allowed; remove other labels: ${others.join(", ")}.`
            //   );
            //   return;
            // }

            core.notice(`OK: release label = ${matched[0]}`);
