name: Release

env:
  IMAGE_NAME: garenmtech1981/wms   # 改成你的 <DockerHub用户名>/<仓库名>

on:
  # 手动触发，选择 bump 类型
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: patch
        type: choice
        options: [major, minor, patch]

  # 当 Release PR 合并到 master 时触发
  pull_request:
    types: [closed]
    branches: [master]   # 主分支如果是 main，这里改成 main

permissions:
  contents: write
  pull-requests: write

jobs:
  # ① 手动触发：生成 Release PR
  create_release_pr:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master (with tags)
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0   # 需要完整历史和 tags

      - name: Find latest tag
        id: lasttag
        shell: bash
        run: |
          TAG=$(git tag --list 'v*' --sort=-version:refname | head -n 1 || true)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: ${TAG:-<none>}"

      - name: Guard - check changes since latest tag
        id: guard
        shell: bash
        run: |
          if [ -z "${{ steps.lasttag.outputs.tag }}" ]; then
            echo "No tag yet -> allow release."
            echo "should_release=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          RANGE="${{ steps.lasttag.outputs.tag }}..HEAD"
          CHANGED=$(git diff --name-only "$RANGE" | grep -Ev '^(package\.json|package-lock\.json|\.github/workflows/release\.yml)$' || true)

          echo "Changed files:"
          echo "$CHANGED"

          if [ -z "$CHANGED" ]; then
            echo "No meaningful changes since ${{ steps.lasttag.outputs.tag }} -> skip."
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Stop if no changes
        if: ${{ steps.guard.outputs.should_release != 'true' }}
        run: echo "Skip creating Release PR: no code changes since last tag."

      - name: Setup Node
        if: ${{ steps.guard.outputs.should_release == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        if: ${{ steps.guard.outputs.should_release == 'true' }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Bump version
        if: ${{ steps.guard.outputs.should_release == 'true' }}
        id: bump
        shell: bash
        run: |
          npm version "${{ github.event.inputs.bump }}" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "New version: $VERSION"

      - name: Create Release PR
        if: ${{ steps.guard.outputs.should_release == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): bump version to v${{ env.VERSION }}"
          branch: release/bump-v${{ env.VERSION }}
          title: "Release: v${{ env.VERSION }}"
          body: |
            This PR was created automatically by GitHub Actions.
            - Bump type: `${{ github.event.inputs.bump }}`
            - New version: `v${{ env.VERSION }}`
          base: master
          labels: release

  # ② Release PR 合并后：构建并推送 Docker 镜像
  build_and_push_on_merge:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Read version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Read version: $VERSION"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t "${{ env.IMAGE_NAME }}:${{ env.VERSION }}" \
                       -t "${{ env.IMAGE_NAME }}:latest" .

      - name: Push image
        run: |
          docker push "${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
          docker push "${{ env.IMAGE_NAME }}:latest"

      - name: Create git tag
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

  # ③ 可选：当 PR 被关闭但未合并时，避免显示红色
  skip_when_closed_without_merge:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR closed without merge. Skipping release."
